Fixing basic logic of killall bash function.
I don't even remember when I wrote this, but it was probably 2 or 3
years ago... Evidently I forgot all about it because it doesn't work. :P
I am amazed that it hasn't interfered with things in all of this time.
I'm sure that I have been using killall and it should have been loaded
in my environment... Maybe I thought I was killing things, but wasn't.
Hell, maybe it failed and I was blaming the system command instead of my
bash function. It's funny if you think about it... I'm not really sure
what this function is even for since it seems to more or less reinvent
the square wheel that is killall, but I assume that I intended to make
it more user friendly (i.e., not loop indefinitely until you ^C).

I could probably enhance this quite a bit with my current level of
experience with bash (and Perl, for that matter), but perhaps I should
rename it so there is never a conflict with the alternative command...

diff --git a/.bash.d/00function.d/killall b/.bash.d/00function.d/killall
--- a/.bash.d/00function.d/killall
+++ b/.bash.d/00function.d/killall
@@ -1,27 +1,38 @@
 function killall
 {
     while [ "$1" ]; do
-        process="$1"
+        local answer;
+        local process="$1"
 
         if [ "$process" == -f -o "$process" == --force ]; then
-            force=1
+            answer=y;
+            shift;
             continue;
         fi
 
-        psaux="`ps aux | grep "$process" | grep -v grep`";
-        pids="`echo "$psaux" | awk '{print $2}' | xargs`";
+        local psaux="`ps aux | grep "$process" | grep -v grep`";
+        local pids="`echo "$psaux" | awk '{print $2}' | xargs`";
+
+        if [ "$pids" == "" ]; then
+            echo "$process not found" 1>&2;
+            shift;
+            continue;
+        fi;
 
         echo "$psaux";
 
-        if [ ! "$force" ]; then
+        if [ "$answer" != y ]; then
             echo "The following PIDs will be KILLed: $pids";
             read -p "Terminate these processes (Y/n) [n] " answer;
-            if [ "$answer" == y -o "$answer" == Y ]; then
-                echo "KILLing..."
-                kill -KILL $pids
-            else
-                echo "Skipping /$process/";
-            fi;
         fi
+
+        if [ "$answer" == y -o "$answer" == Y ]; then
+            echo "KILLing..."
+            kill -KILL $pids
+        else
+            echo "Skipping $process";
+        fi;
+
+        shift;
     done
 }
